services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: playto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d playto_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      PLAYTO_TOKEN_SALT: ${PLAYTO_TOKEN_SALT}
      PLAYTO_TOKEN_MAX_AGE_SECONDS: ${PLAYTO_TOKEN_MAX_AGE_SECONDS:-604800}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      POSTGRES_DB: playto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
